<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="DTOs\**" />
	  <EmbeddedResource Remove="DTOs\**" />
	  <None Remove="DTOs\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Viewer.PoC.ViewModel\Viewer.PoC.Model.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="WindowsBase">
	    <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\WindowsBase.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
